export const ArenaTiles = 
[{
    "id": 1,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 2,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 3,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 4,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 5,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 6,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 7,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 8,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 9,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 10,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 11,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 12,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 13,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 14,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 15,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 16,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 17,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 18,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 19,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 20,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 21,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 22,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 23,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 24,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 25,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 26,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 27,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 28,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 29,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 30,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 31,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 32,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 33,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 34,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 35,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 36,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 37,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 38,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 39,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 40,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 41,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 42,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 43,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 44,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 45,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 46,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 47,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 48,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 49,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 50,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 51,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 52,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 53,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 54,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 55,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 56,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 57,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 58,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 59,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 60,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 61,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 62,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 63,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }, {
    "id": 64,
    "bot": 0,
    "isCollided": false,
    "isBot": false
  }]
  

export const BooleBots = [{
    "id": 1,
    "color": "Turquoise"
  }, {
    "id": 2,
    "color": "Red"
  }, {
    "id": 3,
    "color": "Orange"
  }, {
    "id": 4,
    "color": "Yellow"
  }]

 